---
title: "Seminar Introduction"
format: html
toc: true
editor: source
---
## Session Overview

Welcome to UP 591: Capstone Seminar!

### Learn

We'll spend time reviewing the goals and expectation of the course as well as our course structure.

### Reflect

We will be joined by experts from the [Illinois Leadership Center](https://leadership.illinois.edu) to review the results of your Clifton Strengths assessment. 

### Review

## Before we Meet

- Complete the Clifton Strengths Assessment by **Wednesday 8/28/2024**.

+ Users are allowed to complete the assessment one time on this portal and can retrieve their previous results anytime. As part of having access to and completing the assessment on the ILC portal, Gallup, Inc. and the ILC staff have access to user results. The ILC does not distribute users’ information to the public. 

- Update your Plan of Study (the Plan of Study template can be found here) and bring to class.

## After we Meet

- Revise and submit your updated Plan of Study.

## Additional Resources

- [Illinois Leadership Center](https://leadership.illinois.edu)
