---
title: "Developing Your 2-Year Professional Development Plan"
format: html
toc: true
editor: source
---
## Session Overview

### Learn

We will be joined by MUP program alums Francesca Lawrence, AICP (Teska Associates) and Eric Van Buskirk, AICP (City of Champaign) who will talk about their use of portfolios as part of their professional development and identification strategy. 

For this panel discussion we will meet jointly with students in UP 401 in TBH 227.

### Reflect

We will conduct a self assessment of the strengths and weaknesses of our professional networks, and will develop strategies for addressing weaknesses in these networks.

We will return to TBH 225 for this session and for our third hour of class.

### Review

We will spend time reviewing job ads, examining stated (and unstated) qualifications, and will develop strategies for responding.

## Before we Meet

1. For our professional network workshop, start to think about your professional contacts and connections. It may be useful to make a list of those professional contacts who you consider to be a resource to you. In class, we will start to organize these contacts and strategize around areas for further network development.

2. For the first 10 minutes of our job ad workshop, I will ask you to identify 1-2 active professional planning job listings that you would consider applying to if you were on the job market right now. You may choose to identify these before we meet, or use the first 10 minutes of our session to search for ads.

## After we Meet

## Additional Resources

**[Francesca S. Lawrence, AICP](https://www.linkedin.com/in/francesca-sallinger-lawrence/)**
Senior Planner
Teska Associates, Inc.
[FSLawrence@TeskaAssociates.com](mailto:FSLawrence@TeskaAssociates.com)

**[Eric Van Buskirk, AICP](https://www.linkedin.com/in/eric-van-buskirk-aicp-62baa6301/)**
[Adjunct Lecturer](https://urban.illinois.edu/people/profiles/eric-van-buskirk-aicp/)
Department of Urban and Regional Planning
University of Illinois at Urbana-Champaign
Senior Planner
Planning and Development Department
City of Champaign
