---
title: "Capstone Deliverables"
format: html
toc: true
sidebar: true
editor: source
---

## What is the Capstone?

The MUP capstone provides MUP students with the opportunity to apply what they have learned through their courses and internships to a specific planning problem or issue, and therefore to demonstrate their professional competence to both the faculty, potential employers, and the public.

## What Components Am I Responsible For?

The MUP Program requires that all students preparing to graduate produce three main deliverables in partial fulfillment of graduation capstone requirements:

1.  The MUP Portfolio
2.  The MUP Poster
3.  A Signed Capstone Exit Form (and the accompanying capstone manuscript for students completing the Project or Thesis options)

### Component Breakdown

These deliverables help to summarize your time and knowledge acquired in the MUP program.

-   **The MUP Portfolio** provides a holistic summary of your professional capacities and vision for practice.

-   **The MUP Poster** summarizes one important work that reflects your professional identity.

-   **The Capstone Exit Form** records both information about your submissions as well as your permission for the library to publicly archive your capstone deliverables. The Exit Form also records your certification as well as needed departmental approvals that you have satisfactorily completed your capstone requirements. This form must be executed before you will recieve credit for UP 591 which is required to graduate.

-   **The Capstone Manuscript** exemplifies your work as a planning practitioner (in the case of the Workshop or Project options) or planning researcher (in the case of the Thesis option). Students completing the workshop option are assessed on their contributions as part of the UP 510 class. Project and Thesis manuscripts are evaluated respectively by the faculty project adviser or thesis committee.

As a department, we use these deliverables in three ways:

1.  To **celebrate and record** your significant accomplishments during your time as a graduate student at Illinois.
2.  To **assess your capacity** to apply key knowledge acquired as a Masters student to advanced practice.
3.  To **assess your learning** in accordance with university and accreditation learning outcomes assessment requirements.

## Capstone Timeline

### General Timeline

**Semester 2 (Spring)**

-   Capstone adoption process begins

**Semester 3 (Fall)**

-   Capstone adoption complete
-   Updated Plan of Study
-   Introduce capstone requirements including portfolio and poster requirements

**Semester 4 (Spring)**

-   Draft poster submission
-   Draft poster review session
-   Department awards ceremony and poster event (finals week)
-   Final deliverables due (finals week)
    -   Digital copy of Masters Poster
    -   Digital copy of MUP Portfolio
    -   Signed Capstone Exit Form (and accompanying final manuscript for Project or Thesis options)

### Key Dates for Spring 2025 Graduates

+-------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date              | Deliverable                                       | Description                                                                                                                                                                                    |
+===================+===================================================+================================================================================================================================================================================================+
| **March 28**      | Draft Project / Thesis to Adviser                 | -   Students pursuing the Project or Thesis pathways submit a complete first draft of their capstones to their adviser for review and comments                                                 |
+-------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **April 17**      | Draft Poster Submission                           | -   Submit your draft poster to the Box file dropbox below.                                                                                                                                    |
|                   |                                                   |                                                                                                                                                                                                |
|                   |                                                   | -   Submissions must follow this naming convention: LastName_FirstName_PosterDraft.pdf                                                                                                         |
+-------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **April 25**      | Draft Poster Review and Markup                    | -   The poster review and markup will take place between 12:00 and 2:00 pm in TBH 227. Please have your poster pinned up in TBH 227 before 12:00 pm.                                           |
|                   |                                                   | -   We will invite you and other students and faculty to provide feedback on your poster (12:00 – 2:00 pm). Please be prepared for your draft poster to be written on and marked up.           |
+-------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **May 8**         | Capstone Poster Presentations and Awards Ceremony | -   Time to celebrate your accomplishments! The Poster Presentations and Awards Ceremony is 5:00 - 7:00 PM in the TBH Blicharski Atrium. This is a public event and all are welcome to attend. |
|                   |                                                   | -   Please print a copy of your final polished poster and pin it up in the Blicharski Atrium between 2:00 pm and 4:30 pm.                                                                      |
|                   |                                                   | -   Event starts at 5:00 PM                                                                                                                                                                    |
|                   |                                                   | -   Awards Ceremony 5:00 PM - 5:30 PM                                                                                                                                                          |
|                   |                                                   | -   5:30 PM - 7:00 PM Talk about and share your work with our broader departmental community, local practitioners, faculty, and alumni.                                                        |
+-------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **May 16**        | Capstone Submission Deadline                      | -   Upload your final capstone deliverables *including adviser signature* before this date (more details below).                                                                               |
+-------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Key Capstone Dates Spring 2025

### Thesis Date Considerations

Thesis submissions are subject to additional timing guidelines established by the Graduate College. The [Thesis Deadlines Calendar](https://calendars.illinois.edu/list/3259) contains specific information about Graduate College thesis deadlines. Specific [guidelines for thesis development](https://grad.illinois.edu/academics/thesis-dissertation) and instructions for [thesis submission](https://grad.illinois.edu/academics/thesis-dissertation/submit-your-thesis) are also available.

It is strongly recommended that you schedule your thesis defense for *at least* 1-2 weeks before the deposit deadline so that you have adequate time to revise your thesis based upon committee comments during your defense. You must also ensure that your thesis submission is properly formatted to [Graduate College guidelines](https://grad.illinois.edu/academics/thesis-dissertation/format-requirements). Incomplete or improperly formatted thesis manuscripts may be rejected by the Department or Graduate College.

## Component Descriptions

### The MUP Portfolio

The MUP Portfolio is a holistic summary of your professional identity including polished examples that represent your practice as a planner. The professional portfolio should be designed to showcase your skills and tell a story of who you are as a professional planner. Show examples that you can tell stories about during an interview. Use the portfolio to communicate your design sense.

**Professional History and Goals** - Include a narrative description of your professional history which describes your professional goals and trajectory as well as your values as a professional. Include in your narrative statement a description of your professional goals for the five-year period after you complete your degree.

**Resume / CV** - Include an up to date version of your resume or curriculum vitae.

**Statement of Impact** - Include a narrative statement describing your vision for the type of impact which you aspire to have in your area or field of work.

**Statement of Leadership** - Include a narrative statement describing your vision for leadership in your area or field of work.

**Work Samples** - Include work samples that best illustrate your professional trajectory and capabilities. Include work samples from your core courses, electives, internship (if applicable and you have permission), capstone, and any other contexts that are relevant.

You may choose the format and structure for your portfolio - this could be an document intended for print, could be a website, or could take another format of your choice. You will need to provide a durable record which the department can evaluate. We also hope that this portfolio will be an important resource as you pursue your next professional or academic steps as you prepare to graduate.

### The MUP Poster

The MUP Poster is a place for you to summarize one significant work that represents your mastery of key urban planning skills. You may choose which work completed during the MUP program which you want to showcase on your poster. For those students pursuing the Project or Thesis capstone pathways, you may choose to design a poster based upon your capstone deliverable, however, this is not required. Likewise, students who completed the workshop pathway may design a poster based upon their contributions to the overall workshop deliverable, however, the poster should focus on distinct individual contributions rather than on the overall workshop outputs. Individuals who completed a group project have the option of designing companion posters with one printed poster per group member.

You will recieve feedback on your draft poster during a poster markup event in April. You will print and display your final poster at the Planning at Illinois capstone reception in May.

#### Poster Requirements

Your poster should be a polished and visually engaging summary of a key piece of work you completed as part of your MUP degree. All posters must meet the following requirements:

- The printed poster should be 30" x 40" (portrait or landscape orientation).
- Your Name - Master of Urban Planning
- Department of Urban + Regional Planning
- University of Illinois at Urbana-Champaign
- The semester in which you are graduating (e.g. Spring 2025)

#### Poster Formatting Tips and Resources

##### 1. Emphasize results, findings, and key takeaways

- Your audience should quickly understand your story
- Literature, history, and sources should be minimal
- Illustrate methods visually using process diagrams or flow charts instead of long narrative descriptions

##### 2. Show, don't tell

- The key is effective visual communication, not lengthy explanations
- Visuals (maps, charts, diagrams, images) should be approximately 3/4 of your poster with the remaining 1/4 text
- Visuals should be informative and self-explanatory, complementing each other to tell a compelling story. 
- Clear captions, annotations, and consistent labeling can help maintain focus on your story.
- Convert tables into charts and diagrams - visuals are faster to process and interpret.

##### 3. Follow basic rules of graphic design

- Design with consistency: use grids, maintain alignment, and avoid crowding
- Develop a visual hierarchy to establish priorities for your audience. Image size can help to reinforce this hierarchy with smaller visuals supporting secondary details.
  + Use colors judiciously and purposefully
  + You are not limited to a white background   + subtle textures, gradients, and muted images can add sophistication but should not overwhelm content.
  + Consider color conventions (e.g., red = caution / danger / important; green = go / environment / good; blue = water / calm); if you include a plan map remember to use land use color conventions.
  + Online design tools can help you find ideal color combinations
  + Limiting yourself to no more than 3-4 main colors generally makes it easier to create a cohesive and impactful visual that projects a professional and polished look.

- Use text sparingly
  + Establish a clear text hierarchy: main points (headlines), subheads, short supporting blurbs (captions, labels, annotations).
  + Use bullets and sentence fragments rather than paragraphs.
  + Limit wrapped text and long text blocks.

- Understand typeface selection and choose fonts with care
  + Title: Approximately 100 pt
  + Heading: 60-70 pt
  + Body test: 36-40 pt
  + Captions: 18-20 pt

- Limit yourself to 2-3 fonts for visual consistency
  + One font for titles and headings
  + One font for body text
  + One font (optional) for captions or annotations

- Use sans serif fonts for headlines (more modern and legible at large sizes)

- Use serif fonts for body text, especially at smaller sizes for readability

- If using a colored background, choose high-contrast fonts (medium or bold weights work best)

- Embrace white space to frame your content and improve readability. This includes negative space around all text and visual elements.

##### 4. Create clear visual flow and navigation

- Use color, font size, and positioning to guide the reader through your content in the intended order
- Two effective layout strategies:
  + Column Layout (newspaper style) - 2-3 vertical columns read left to right and top to bottom
  + Central Focus (billboard style) - One bold central message with supporting visuals around it
- Directional cues (arrows, numbering,subtle design elements) can help lead the eye

::: callout-tip
You can find examples of prior MUP posters through [UIUC IDEALS](https://www.ideals.illinois.edu/collections/1318)
:::

### The Capstone Exit Form

The [Capstone Exit Form](https://web.faa.illinois.edu/app/uploads/sites/2/2023/08/04_CapstoneExit.pdf) is the main transmittal form for your final capstone products. 

- For students pursuing the workshop option, the Graduate Program Adviser (Ben LeRoy) will sign your capstone exit form, certifying that you have completed two UP 510 Plan Making Workshop courses. 
- For students pursuing the Project or Thesis options, your project or thesis adviser will sign the form indicating that you have satisfactorily completed your project or have successfully defended and deposited your thesis.
- Regardless of your capstone pathway, please indicate whether you give permission for your capstone materials (poster, portfolio, and project or thesis) to be published in the UIUC IDEALS archive.
- After reviewing your final capstone materials uploaded to Box, the Director of Graduate Studies will email you the final executed exit form certifying that you have satisfactorily completed all capstone exit requirements for the Master of Urban Planning degree.

## Resources

-   [MUP Program Handbook](https://web.faa.illinois.edu/app/uploads/sites/2/2024/08/MUP-Program-Handbook-2024-2025.pdf)

-   [UIUC IDEALS database](https://www.ideals.illinois.edu)

-   [MUP Projects (1970 - 2018)](https://www.library.illinois.edu/cpla/theses/mpurp/)

-   [MUP Theses (1959 - 2018)](https://www.library.illinois.edu/cpla/theses/mturp/)

-   [Professor Greenlee's MUP Capstone Guidance](https://andrew-greenlee.com/resources/mup_capstone)

## Submitting your Capstone Exit Materials

### Draft Poster Submission

You will submit your draft poster before the April draft poster pin up event.

-   LastName_FirstName_DraftPoster.pdf - your draft poster submission

where LastName is your surname (last name) and FirstName is your first name.

### Capstone Submission

During finals week in May you will upload your capstone exit form with advisor signature, final poster, final portfolio, and project or thesis manuscript (for Project / Thesis pathways). Please follow these naming conventions for your Box uploads:

-   LastName_FirstName_ExitForm.pdf - exit form signed by your advisor

-   LastName_FirstName_Poster.pdf - your final poster

-   LastName_FirstName_Portfolio.pdf - your final portfolio

-   LastName_FirstName_Project.pdf - your final project manuscript (for those completing the project pathway)

-   LastName_FirstName_Thesis.pdf - your final thesis manuscript as deposited with the Graduate College (for those completing the thesis pathway)

After you upload your Exit Materials, please email the Director of Graduate Studies who will review your materials, and given satisfactory completion of all exit requirements who will sign off on your Capstone Exit Form to certify your completion of all capstone requirements associated with the MUP degree.

::: panel-tabset
## Draft Poster

<iframe src="https://uofi.app.box.com/f/c56a6a9cef7648b3a11e8e35d3950087" height="900" width="800">

</iframe>

## Final Deliverables

<iframe src="https://uofi.app.box.com/f/c4f82d7d71e3488caacda83d23f0484b" height="900" width="800">

</iframe>
:::
