---
title: "Seminar Milestones"
format: html
toc: true
sidebar: true
editor: source
---

There are six major milestones that you will complete across the two semesters of this seminar:

+---------------------------------------------------------+------------------+----------------------+
| Deliverable                                             | Pathway          | Due Date             |
+=========================================================+==================+======================+
| [Plan of Study Update](01_planofstudy.qmd)              | All              | 9/6/2024             |
+---------------------------------------------------------+------------------+----------------------+
| [Capstone Adoption](02_capstoneadoption.qmd)            | All              | 9/9/2024             |
+---------------------------------------------------------+------------------+----------------------+
| [Monthly Progress Memorandum](03_progressmemo.qmd)      | Project / Thesis | September: 10/4/2024 |
|                                                         |                  |                      |
|                                                         |                  | October: 11/1/2024   |
|                                                         |                  |                      |
|                                                         |                  | November: 12/6/2024  |
|                                                         |                  |                      |
|                                                         |                  | December: 1/24/2025  |
|                                                         |                  |                      |
|                                                         |                  | January: 2/7/2025    |
|                                                         |                  |                      |
|                                                         |                  | February: 3/7/2025   |
|                                                         |                  |                      |
|                                                         |                  | March: 4/4/2025      |
|                                                         |                  |                      |
|                                                         |                  | April: 5/2/2025      |
+---------------------------------------------------------+------------------+----------------------+
| [Professional Development Plan](04_developmentplan.qmd) | All              | 10/4/2024            |
+---------------------------------------------------------+------------------+----------------------+
| [MUP Portfolio](05_portfolioqmd.qmd)                    | All              | 5/16/2025            |
+---------------------------------------------------------+------------------+----------------------+
| [Capstone Deliverables](06_capstone.qmd)                | All              | TBD                  |
+---------------------------------------------------------+------------------+----------------------+

It is important to review the details of each of these milestones, particularly since some have both draft and final components with separate deliverable dates. You will also find submission details and requirements for each milestone included with its description.
